apiVersion: v1
kind: Service
metadata:
  name: {{ include "transceiver-exporter.fullname" . }}
  labels:
    {{- include "transceiver-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "transceiver-exporter.selectorLabels" . | nindent 4 }}
